### ISSUE TITLE
Add GRBio info

### ISSUE THREAD

**Issue by redmondn** [SIBarcodeNetwork/ReadtheDocsMaster#1]
We need to add GRBio info - not sure of best place to add it yet.

**Comment by MikeTrizna** [comment]
Right now, it seems like the best place to talk about it is in a new section on "Validation Rules" that would go right before the [Column Definitions section](http://sibarcodenetwork.readthedocs.io/en/latest/fims_spreadsheet_pop.html#column-definitions) on the _Populating the FIMS Spreadsheet_ page. Do you think that would be putting too much into a single documentation page?
